SELECT * FROM store_sales ss
 join date_dim ss_sold_date on ss.ss_sold_date_sk = ss_sold_date.d_date_sk
 join time_dim ss_sold_time on ss.ss_sold_time_sk = ss_sold_time.t_time_sk
 join item ss_item on ss.ss_item_sk = ss_item.i_item_sk
 join customer ss_customer on ss.ss_customer_sk = ss_customer.c_customer_sk
 join customer_demographics ss_cdemo on ss.ss_cdemo_sk = ss_cdemo.cd_demo_sk
 join household_demographics ss_hdemo on ss.ss_hdemo_sk = ss_hdemo.hd_demo_sk
 join customer_address ss_addr on ss.ss_addr_sk = ss_addr.ca_address_sk
 join promotion ss_promo on ss.ss_promo_sk = ss_promo.p_promo_sk
 join store ss_store on ss.ss_store_sk = ss_store.s_store_sk
 join date_dim ss_s_closed_date on ss_store.s_closed_date_sk = ss_s_closed_date.d_date_sk
 join item ss_p_item on ss_promo.p_item_sk = ss_p_item.i_item_sk
 join date_dim ss_p_start_date on ss_promo.p_start_date_sk = ss_p_start_date.d_date_sk
 join date_dim ss_p_end_date on ss_promo.p_end_date_sk = ss_p_end_date.d_date_sk
 join customer_demographics ss_c_current_cdemo on ss_customer.c_current_cdemo_sk = ss_c_current_cdemo.cd_demo_sk
 join date_dim ss_c_first_shipto_date on ss_customer.c_first_shipto_date_sk = ss_c_first_shipto_date.d_date_sk
 join date_dim ss_c_first_sales_date on ss_customer.c_first_sales_date_sk = ss_c_first_sales_date.d_date_sk
 join date_dim ss_c_last_review_date on CAST(ss_customer.c_last_review_date as INT) = ss_c_last_review_date.d_date_sk
 join customer_address ss_c_current_addr on ss_customer.c_current_addr_sk = ss_c_current_addr.ca_address_sk
 join household_demographics ss_c_current_hdemo on ss_customer.c_current_hdemo_sk = ss_c_current_hdemo.hd_demo_sk
 join income_band ss_hd_income_band on ss_hdemo.hd_income_band_sk = ss_hd_income_band.ib_income_band_sk
 join inventory ss_inv on ss_item.i_item_sk = ss_inv.inv_item_sk
 join date_dim ss_inv_date on ss_inv.inv_date_sk = ss_inv_date.d_date_sk
 join warehouse ss_inv_warehouse on ss_inv.inv_warehouse_sk = ss_inv_warehouse.w_warehouse_sk
 full outer join store_returns sr on ss.ss_ticket_number = sr.sr_ticket_number
 join date_dim sr_returned_date on sr.sr_returned_date_sk = sr_returned_date.d_date_sk
 join time_dim sr_return_time on sr.sr_return_time_sk = sr_return_time.t_time_sk
 join item sr_item on sr.sr_item_sk = sr_item.i_item_sk
 join customer sr_customer on sr.sr_customer_sk = sr_customer.c_customer_sk
 join customer_demographics sr_cdemo on sr.sr_cdemo_sk = sr_cdemo.cd_demo_sk
 join household_demographics sr_hdemo on sr.sr_hdemo_sk = sr_hdemo.hd_demo_sk
 join customer_address sr_addr on sr.sr_addr_sk = sr_addr.ca_address_sk
 join store sr_store on sr.sr_store_sk = sr_store.s_store_sk
 join reason sr_reason on sr.sr_reason_sk = sr_reason.r_reason_sk
 join date_dim sr_s_closed_date on sr_store.s_closed_date_sk = sr_s_closed_date.d_date_sk
 join customer_demographics sr_c_current_cdemo on sr_customer.c_current_cdemo_sk = sr_c_current_cdemo.cd_demo_sk
 join date_dim sr_c_first_shipto_date on sr_customer.c_first_shipto_date_sk = sr_c_first_shipto_date.d_date_sk
 join date_dim sr_c_first_sales_date on sr_customer.c_first_sales_date_sk = sr_c_first_sales_date.d_date_sk
 join date_dim sr_c_last_review_date on CAST(sr_customer.c_last_review_date as INT) = sr_c_last_review_date.d_date_sk
 join customer_address sr_c_current_addr on sr_customer.c_current_addr_sk = sr_c_current_addr.ca_address_sk
 join household_demographics sr_c_current_hdemo on sr_customer.c_current_hdemo_sk = sr_c_current_hdemo.hd_demo_sk
 join income_band sr_hd_income_band on sr_hdemo.hd_income_band_sk = sr_hd_income_band.ib_income_band_sk
 join inventory sr_inv on sr_item.i_item_sk = sr_inv.inv_item_sk
 join date_dim sr_inv_date on sr_inv.inv_date_sk = sr_inv_date.d_date_sk
 join warehouse sr_inv_warehouse on sr_inv.inv_warehouse_sk = sr_inv_warehouse.w_warehouse_sk