drop table bigTable;
create table if not exists bigTable
(
    timest                        timestamp ,
    ss_ss_sold_date_sk             string   ,
    ss_ss_sold_time_sk             string   ,
    ss_ss_item_sk                  string   ,
    ss_ss_customer_sk              string   ,
    ss_ss_cdemo_sk                 string   ,
    ss_ss_hdemo_sk                 string   ,
    ss_ss_addr_sk                  string   ,
    ss_ss_store_sk                 string   ,
    ss_ss_promo_sk                 string   ,
    ss_ss_quantity                  double  ,
    ss_ss_list_price               double   ,
    ss_ss_sales_price              double   ,
    ss_ss_ext_sales_price          double   ,
    ss_ss_ext_wholesale_cost       double   ,
    ss_ss_coupon_amt               double   ,
    ss_ss_net_profit               double   ,
    ss_sold_date_d_date_sk         string   ,
    ss_sold_date_d_date           date      ,
    ss_sold_date_d_month_seq       double   ,
    ss_sold_date_d_year            double   ,
    ss_sold_date_d_moy             double   ,
    ss_sold_date_d_day_name        string   ,
    ss_sold_time_t_time_sk         double   ,
    ss_sold_time_t_time            double   ,
    ss_sold_time_t_hour            double   ,
    ss_sold_time_t_minute          double   ,
    ss_sold_time_t_second          double   ,
    ss_item_i_item_sk              string   ,
    ss_item_i_item_id              string   ,
    ss_item_i_item_desc            string   ,
    ss_item_i_current_price        double   ,
    ss_item_i_brand_id             double   ,
    ss_item_i_brand                string   ,
    ss_item_i_class                string   ,
    ss_item_i_category_id          double   ,
    ss_item_i_category             string   ,
    ss_item_i_manufact_id          string   ,
    ss_item_i_manufact             string   ,
    ss_item_i_size                 string   ,
    ss_item_i_manager_id           double   ,
    ss_customer_c_customer_sk      string   ,
    ss_customer_c_current_addr_sk  string   ,
    ss_cdemo_cd_demo_sk            string   ,
    ss_cdemo_cd_gender             string   ,
    ss_cdemo_cd_marital_status     string   ,
    ss_cdemo_cd_education_status   string   ,
    ss_hdemo_hd_demo_sk            string   ,
    ss_hdemo_hd_dep_count          double   ,
    ss_addr_ca_address_sk          string   ,
    ss_addr_ca_state               string   ,
    ss_addr_ca_zip                 string   ,
    ss_addr_ca_country             string   ,
    ss_promo_p_promo_sk            string   ,
    ss_promo_p_channel_email       string   ,
    ss_promo_p_channel_event       string   ,
    ss_store_s_store_sk            string   ,
    ss_store_s_store_id            string   ,
    ss_store_s_store_name          string   ,
    ss_store_s_county              string   ,
    ss_store_s_state               string   ,
    ss_store_s_zip                 string   ,
    ss_store_s_gmt_offset          double   ,
    ss_c_current_addr_ca_address_sk  string ,
    ss_c_current_addr_ca_state     string   ,
    ss_c_current_addr_ca_zip       string   ,
    ss_c_current_addr_ca_country   string

)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ","
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INPATH '/data/tpcds/1g/store_filtered_join.csv/part-00000-17ff6dab-cf08-4936-a695-c73d0927ed43-c000.csv' INTO TABLE bigtable;

drop table orcBigTable;
create table if not exists orcBigTable
(
    timest                        timestamp ,
    ss_ss_sold_date_sk             string   ,
    ss_ss_sold_time_sk             string   ,
    ss_ss_item_sk                  string   ,
    ss_ss_customer_sk              string   ,
    ss_ss_cdemo_sk                 string   ,
    ss_ss_hdemo_sk                 string   ,
    ss_ss_addr_sk                  string   ,
    ss_ss_store_sk                 string   ,
    ss_ss_promo_sk                 string   ,
    ss_ss_quantity                  double  ,
    ss_ss_list_price               double   ,
    ss_ss_sales_price              double   ,
    ss_ss_ext_sales_price          double   ,
    ss_ss_ext_wholesale_cost       double   ,
    ss_ss_coupon_amt               double   ,
    ss_ss_net_profit               double   ,
    ss_sold_date_d_date_sk         string   ,
    ss_sold_date_d_date           date      ,
    ss_sold_date_d_month_seq       double   ,
    ss_sold_date_d_year            double   ,
    ss_sold_date_d_moy             double   ,
    ss_sold_date_d_day_name        string   ,
    ss_sold_time_t_time_sk         double   ,
    ss_sold_time_t_time            double   ,
    ss_sold_time_t_hour            double   ,
    ss_sold_time_t_minute          double   ,
    ss_sold_time_t_second          double   ,
    ss_item_i_item_sk              string   ,
    ss_item_i_item_id              string   ,
    ss_item_i_item_desc            string   ,
    ss_item_i_current_price        double   ,
    ss_item_i_brand_id             double   ,
    ss_item_i_brand                string   ,
    ss_item_i_class                string   ,
    ss_item_i_category_id          double   ,
    ss_item_i_category             string   ,
    ss_item_i_manufact_id          string   ,
    ss_item_i_manufact             string   ,
    ss_item_i_size                 string   ,
    ss_item_i_manager_id           double   ,
    ss_customer_c_customer_sk      string   ,
    ss_customer_c_current_addr_sk  string   ,
    ss_cdemo_cd_demo_sk            string   ,
    ss_cdemo_cd_gender             string   ,
    ss_cdemo_cd_marital_status     string   ,
    ss_cdemo_cd_education_status   string   ,
    ss_hdemo_hd_demo_sk            string   ,
    ss_hdemo_hd_dep_count          double   ,
    ss_addr_ca_address_sk          string   ,
    ss_addr_ca_state               string   ,
    ss_addr_ca_zip                 string   ,
    ss_addr_ca_country             string   ,
    ss_promo_p_promo_sk            string   ,
    ss_promo_p_channel_email       string   ,
    ss_promo_p_channel_event       string   ,
    ss_store_s_store_sk            string   ,
    ss_store_s_store_id            string   ,
    ss_store_s_store_name          string   ,
    ss_store_s_county              string   ,
    ss_store_s_state               string   ,
    ss_store_s_zip                 string   ,
    ss_store_s_gmt_offset          double   ,
    ss_c_current_addr_ca_address_sk  string ,
    ss_c_current_addr_ca_state     string   ,
    ss_c_current_addr_ca_zip       string   ,
    ss_c_current_addr_ca_country   string

) STORED AS ORC;

INSERT OVERWRITE TABLE default.orcBigTable select * from default.BigTable;
